# These are supported funding model platforms

github: [joneng032] # Replace with your GitHub username
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift platform/username/package name
# community_bridge: # Replace with your Community Bridge project-name
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# otechie: # Replace with your Otechie username
# custom: # Replace with a single custom sponsorship URL