name: List MAUI Compile items and fail on duplicate-type warnings

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  audit-build:
    name: Audit build and compile items
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Start with Windows runs only to ensure hosted runners have required capabilities.
        # Expanding to Android/iOS/macOS TFMs requires additional runner setup (workloads, SDKs).
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.x"

      - name: Restore
        run: dotnet restore "reserve flow ai 2026.sln"

      - name: Restore .NET workloads
        # Ensure required MAUI workloads are available on the runner. This mitigates NETSDK1147.
        run: |
          dotnet workload restore || true
          dotnet workload list || true

      - name: Build & List Compile Items (fail on CS0436/CS0579)
        # This builds and runs the custom ListCompileItems target added to the MAUI project.
        # We treat CS0436/CS0579 as errors to prevent duplicate-type regressions.
        # Quote the -warnaserror argument so PowerShell (used on windows runners) doesn't split on the semicolon.
        run: |
          dotnet build "reserve flow ai 2026.csproj" -c Debug "-warnaserror:CS0436;CS0579" -t:ListCompileItems

      - name: Validate compile_items files
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path obj -Recurse -Filter "compile_items_*.txt" -File -ErrorAction SilentlyContinue
          if (-not $files -or $files.Count -eq 0) {
            Write-Error "No compile_items_*.txt files found under obj/. The ListCompileItems target may have not run or wrote files to an unexpected location."
            exit 1
          }

          $bad = @()
          foreach ($f in $files) {
            # Read file lines and check for at least one non-whitespace line
            try {
              $lines = Get-Content -Path $f.FullName -ErrorAction Stop | ForEach-Object { $_.ToString().Trim() } | Where-Object { $_ -ne '' }
            } catch {
              $lines = @()
            }
            if (-not $lines -or $lines.Count -eq 0) {
              $bad += $f.FullName
            }
          }

          if ($bad.Count -gt 0) {
            Write-Error "Found compile_items files with no meaningful content:`n$($bad -join "`n")"
            exit 1
          }

          Write-Host "Found $($files.Count) compile_items files with meaningful content. Proceeding to package artifacts."

      - name: Package compile_items artifacts (per-TFM zips)
        shell: pwsh
        run: |
          $outDir = "artifacts"
          New-Item -ItemType Directory -Path $outDir -Force | Out-Null
          $files = Get-ChildItem -Path obj -Recurse -Filter "compile_items_*.txt" -File
          if (-not $files -or $files.Count -eq 0) { Write-Error "No files to compress"; exit 1 }

          # Group by filename without extension (compile_items_<tfm>) so each group becomes a per-TFM zip
          $groups = $files | Group-Object { [IO.Path]::GetFileNameWithoutExtension($_.Name) }
          foreach ($g in $groups) {
            $zipName = Join-Path $outDir ("$($g.Name).zip")
            $paths = $g.Group | Select-Object -ExpandProperty FullName
            Compress-Archive -Path $paths -DestinationPath $zipName -Force
            Write-Host "Created $zipName (files: $($paths.Count))"
          }

          # Also create a combined zip for convenience
          $allPaths = $files | Select-Object -ExpandProperty FullName
          Compress-Archive -Path $allPaths -DestinationPath "$outDir/compile_items_all.zip" -Force

      - name: Upload compile_items artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compile-items
          path: |
            artifacts/compile_items_all.zip
            obj/**/compile_items_*.txt

      - name: Show summary
        run: |
          echo "Uploaded compile_items_*.txt artifacts and a packaged zip. If this job fails with CS0436/CS0579, inspect the artifacts to discover duplicate sources."
