name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Build Capacitor Windows
        run: npm run capacitor:build:electron
        if: contains(github.ref, 'v')

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes

            See [CHANGELOG.md](CHANGELOG.md) for details.

            ## Installation

            **Windows Installer**: Download `reserve-flow-capacitor Setup 1.0.0.exe` from the assets below.

            For other platforms or development:

            ```bash
            git clone https://github.com/joneng032/reserve_flow_2026.git
            cd reserve_flow_2026
            npm install
            npm run capacitor:build:electron  # Windows
            npm run capacitor:build:ios       # iOS
            npm run capacitor:build:android   # Android
            npm run build                     # Web
            ```
          draft: false
          prerelease: false
